# Dagster webserver and daemon image (latest stable)
# See: https://docs.dagster.io/deployment/oss/deployment-options/docker

FROM python:3.10-slim

RUN pip install --no-cache-dir \
    dagster==1.12.14 \
    dagster-graphql==1.12.14 \
    dagster-webserver==1.12.14 \
    dagster-postgres==0.28.14 \
    dagster-docker==0.28.14

ENV DAGSTER_HOME=/opt/dagster/dagster_home/
RUN mkdir -p $DAGSTER_HOME
COPY dagster.yaml workspace.yaml $DAGSTER_HOME
WORKDIR $DAGSTER_HOME
